- parsevasp/poscar.py
fixes #1
The flag is added to the constructor, so that the decision of whether to order sites is made per instance and not during the call to `_write`. I think it should be less error prone this way.
Testing was done in an iPython session with a deliberately badly ordered POSCAR file.
> add flag to poscar.Poscar init to conserve site ordering

- parsevasp/incar.py
- parsevasp/kpoints.py
- parsevasp/outcar.py
- parsevasp/poscar.py
- parsevasp/vasprun.py
- setup.py
- tox.ini
This is an attempt at creating compatibility with Python 3.6.
- Added py36 to tox environments
- Replaced direct imports (e.g. ``import utils``) with relative ones (``from . import utils``)
- Use ``past.builtins.basestring`` instead of ``str`` and ``unicode`` for string type matching
- Use ``six.iteritems`` instead of the ``.iteritems()`` method
- Remove some unused imports.
Added dependencies: ``six``, ``future``.
> Add py36 to tox and fix upcoming issues.

- parsevasp/incar.py
Due to all the fun asterix options of MAGMOM, including the problem of explicitly dumping the values, we just eat MAGMOM as a string and pass it along untouched.
> Made exception for MAGMOM, we now take it as is, as a string

- MANIFEST.in
In the previous commit which added `setup.json` it was not included in the manifest and is thus missing at pypi. Added in this commit.
> Added setup.json to the manifet

- parsevasp/outcar.py
- test/OUTCAR_MAG_SINGLE
- test/test_outcar.py
If you have one atom per unit cell the format of the magnetization information is different than if you have multiple atoms in your cell. This has been fixed by adding an extra check to see if the next line after the first magnetization output if blank.
> Fixed issue in magnetization parsing for small cells

- .github/workflows/ci.yml
In order to try to fix timeout issues as per https://github.com/codecov/codecov-action/issues/37 we here update to use latest v1 of `codecov`.
> Updated codecov version

- parsevasp/stream.py
- parsevasp/vasprun.py
Here we add a function that returns `True` if the xml is truncated. Previously the `lxml` parser entered recovery mode and the parser tried to parse quantities. This is okey, but sometimes this fails, depending on why and where the xml is truncated. A function was thus added which can be called to check if it has been truncated and then the caller can act accordingly. In addition we fixed the history of the stream parser. When this flag is set to `True` we also store similar streams if they occur multiple times. If `False` we only store the first occurrence.
> Fixed history for stream parser and added xml truncation function

- parsevasp/outcar.py
- parsevasp/vasprun.py
- tests/test_outcar.py
- tests/test_xml_event.py
- tests/test_xml_regular.py
Timing data can be very useful for benchmarks, convergence
testings.
The extraction of NELM/NSW is needed for determining whether
the electronic/ionic convergence is reached since vasp always
pretends they are converged once the maximum step is reached.
> Add parsing of timing data and NELM, NSW

- parsevasp/vasprun.py
- tests/test_xml_event.py
- tests/test_xml_regular.py
Here we implement the parsing of additional energies and add tests for the self-consistent return of the energies. In addition we parse the VASP version which we will use to e.g. detect the bug that exists between the sc step energies and the final energy printed in the XML file. This is fixed in VASP 6 and thus we need to perform a check for this.
> Add parsing of other energies and detect version

- parsevasp/stream.yml
- tests/test_stream.py
Added more stream items for checking.
Note that IBZKPT is a special case as multiple errors can have this, some of them are actually warnings are not fatal. Hence, I set it to `recovery: true`.
As discussed the suggests are removed unless we are sure it is the right one.
> More stream items for checking

- parsevasp/vasprun.py
- tests/test_stream.py
- tests/test_xml_event.py
- tests/test_xml_regular.py
The `final` tag previously used for the last ionic step is replaced by `last` in order
to release `final` for use for e.g. the total energy that is present after the electronic steps
are complated (includes potential corrections). In addition, we remove the two entries (`initial` and `final` that was previously present for static runs). For static runs, only one entry is now returned. This means that now, if one needs both the `initial` and `last` property, the only way to get this is by parsing all the ionic entries by enabling `status=all`. In addition it is now possible to parse multiple total energy types. Tests have also been modified accordingly.
> Updated parsing of total energies

- parsevasp/vasprun.py
- tests/test_xml_regular.py
The `laset_line` of the XML file returned is a byte object and previously it was compared to a string so the function always returns `True` and the XML is considered as truncated. 
In practice, sometimes it is `b'</modeling>\n'` some times it is `b'</modeling>', both cases are supported now. ~~Not sure why!~~ might be related to whether a file object or file path was used?
A test is added to make sure the truncation detection works as expected.
> Fix truncate detection

- parsevasp/stream.yml
Here we add an error that occur if you e.g. set `NSW` but forget to set `IBRION` or `POTIM`.
> Added error that can happen if you only set NSW

- parsevasp/stream.yml
Here we add an error that appear if you specify `MAGMOM` and not `ISPIN=2`
> Added MAGMOM error

- parsevasp/incar.py
Here we remove the erroneous link between the `Incar` and `IncarItem` class with respect to error messages.
> Removed link to error messages between Incar and IncarItem

- parsevasp/outcar.py
In VASP6 the output can be like:
>
Total CPU time used (sec):       68.875
User time (sec):       67.104
System time (sec):        1.771
Elapsed time (sec):       72.427
Maximum memory used (kb):      188368.
Average memory used (kb):          N/A
Minor page faults:       102806
Major page faults:            1
Voluntary context switches:         4522
Hence, we have to handle the case where the values are not numbers but `N/A`. If that is the case, the relevant values are set to `None`.
> Fix timiming/memory lines being be N/A in VASP

- parsevasp/doscar.py
- parsevasp/utils.py
Fixed an issue with the comment of the system being overridden by the iterations in the parser. Also removed splitting of the string used for the comment.
> Fixed splitting of comments in DOSCAR parser

- parsevasp/eigenval.py
- tests/test_doscar.py
- tests/test_eigenval.py
Here we remove the split of the string that governs the system comment. Also cleaned tests.
> Fixed split of system for EIGENVAL and tests

- parsevasp/kpoints.py
Here we fix a bug which caused the `tetra` key to be an empty list if tetrahedron information was not found in the `KPOINTS`. This later cased the `write` to fail for instance.
> Fixed tetra is None if not found

- parsevasp/eigenval.py
- tests/test_eigenval.py
We replace the `bands` terminology unless we explicitly describe the concatenation of eigenvalues across several k-points, e.g. `num_bands` as `num_eigenvalues` would potentially be a bit misleading as it typically can also run over several k-points. Hence, some of the bands terminology is kept, but not for the data containers themselves.
> Replaced bands data container names with eigenvalues

- parsevasp/outcar.py
- tests/OUTCAR.crashed
- tests/test_outcar.py
Fix https://github.com/aiida-vasp/parsevasp/issues/94
When a VASP calculation crashes before starting SCF iterations,
we fail to parse OUTCAR. This commit implements to report an error message
in such a situation.
> Add error message for incomplete OUTCAR

- parsevasp/base.py
- tests/test_poscar.py
Fix the logger that previously changes the global setting. 
Each class now gets its own logger. Should now behave like this:
```python
In [10]: p = Poscar(file_path="tmp/POSCAR")
In [11]: p._logger.debug("Foo")
2022-02-09 10:26:02,840 - parsevasp.poscar.Poscar - DEBUG - Foo
```
> Fix logging

- parsevasp/vasprun.py
- tests/gw.xml
- tests/test_xml_event.py
- tests/test_xml_regular.py
Here we add corrections so that reading GW calcs works. Also added a test to make sure we can read a `vasprun.xml` from such a calculation properly.
> Added bugfixes to make sure GW vasprun can be read and added test

- parsevasp/incar.py
- parsevasp/kpoints.py
- parsevasp/outcar.py
- parsevasp/poscar.py
- parsevasp/stream.yml
- setup.json
We here add the detection of the issue of the topmost band is occupied. Also, we add `NBANDS` to `run_status` to be able to act on this information. Removed `six` as we only support Python > 3.
> Added band occupation to stream handler, nbands to run_status, removed six

- parsevasp/vasprun.py
Simple correction for the docstring and a fix to check that we supply a list for `etype`.
> Fixed docstring for the status when getting the energies

- parsevasp/potcar.py
- tests/POTCAR
- tests/test_potcar.py
Adding parsing of the metadata of the potential directly to a potcar parser so that we do not have to depend on pymatgen.
Closes #125.
> 125 potcar metada is not parsed

- parsevasp/incar.py
- parsevasp/kpoints.py
- parsevasp/poscar.py
- parsevasp/stream.py
- parsevasp/vasprun.py
- pyproject.toml
Here we remove our usage of `past` and thus the `future` dependency. In addition, we had to address #123 to fix linting runs on Python 3.11. This also triggered various other updates to the linting.
Closes #123, #126.
> Removed future dep and aiida core pylint dep pinning

- .github/workflows/ci.yml
The used actions was old and rely on deprecated Node 12.
> Moved GitHub actions to Node 16 deps

- parsevasp/potcar.py
Here we add a few more details about some of the code from `pymatgen` that was used in the POTCAR metadata parser.
> Added more info regaring the use of pymatgen parsing of POTCAR
